name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Sign Android release
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: /app/build/outputs/apk/release/
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: /app/build/outputs/apk/release/app-release-signed.apk
