name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Android
      run: ./gradlew build
      shell: bash
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: app/build/outputs/apk/release/app-release-unsigned.apk
